- name: WordPress | Generate conf
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: "{{ web_owner }}"
    group: "{{ web_group }}"
    mode: '0644'
  notify: Restart Apache
