apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5.2-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql.dev.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: wp_user
            - name: WORDPRESS_DB_PASSWORD
              value: wp_pass
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
            - containerPort: 80
