Vagrant.configure("2") do |config|
  
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "68.68.68.11"
    client.vm.provision "shell", path: "provisionForClient.sh", args: ["client"]
  end
  
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "68.68.68.10"
    server.vm.provision "shell", path: "provisionForServer.sh", args: ["server"]
  end

  

end
