---
# tasks file for mysql
# check_mysql

- name: Mysql | Check Start
  become: true
  service:
    name: "{{ mysql_service_name[ansible_os_family] }}"
    state: started
    enabled: true
  notify: Restart MySQL