version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_CONF_PATH}:/var/lib/mysql
    networks:
      - backend

  app:
    image: wordpress:latest
    container_name: wp-app
    restart: always
    environment:  
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_HOME: ${WORDPRESS_HOME}
    volumes:
     - ${WORDPRESS_CONF_PATH}:/var/www/html
    networks:
      - backend
      - frontend

  proxy:
    image: nginx:alpine
    container_name: wp-proxy
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge