apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_TABLE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_TABLE_PREFIX
            - name: WORDPRESS_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_DEBUG
            - name: WORDPRESS_CONFIG_EXTRA
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: WORDPRESS_CONFIG_EXTRA
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wp-storage
              mountPath: /var/www/html
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: wp-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress-chart.fullname" . }}-pvc
