apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.wordpress.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.storageClass }}
  local:
    path: {{ .Values.wordpress.storagePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
