apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage }}
