apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
