apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Values.namespace }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.dbHost | quote }}
  WORDPRESS_TABLE_PREFIX: {{ .Values.wordpress.tablePrefix | default "wp_" | quote }}
  WORDPRESS_DEBUG: {{ .Values.wordpress.debug | default "false" | quote }}
  WORDPRESS_CONFIG_EXTRA: {{ .Values.wordpress.extraConfig | default "" | quote }}
